name: Run Pytest on dev branch
on: 
    push:
        branches:
            - dev
    workflow_dispatch:  # Magic line to enable manual workflow runs with the "Run workflow" button
        inputs: {} 
jobs:
    execute_pytest:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup python version
              uses: actions/setup-python@v2
              with:
                python-version: 3.11

            - name: run pytest
              run: make test
