name: Run Pytest and push to the Test PyPI registry
on: 
    push:
        branches:
            - main
            - master
    workflow_dispatch:  # Magic line to enable manual workflow runs with the "Run workflow" button
        inputs: {} 
jobs:
    execute_pytest:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup python version
              uses: actions/setup-python@v2
              with:
                python-version: 3.11

            - name: run pytest
              run: make test
    build:
        needs: execute_pytest
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: setup python version
              uses: actions/setup-python@v2
              with:
                    python-version: 3.11
            - name: build the binary wheel and source tarball
              run: make build
            - name: Store the distribution packages
              uses: actions/upload-artifact@v3
              with:
                name: dependencytrees-distributions
                path: exercise2/dist/
        
    publish-to-testpypi:
        name: Publish distribution to TestPyPI
        needs: build
        runs-on: ubuntu-22.04
    
        environment:
          name: testpypi
          url: https://test.pypi.org/p/dependencytrees
    
        permissions:
          id-token: write  # IMPORTANT: mandatory for trusted publishing
    
        steps:
        - name: Download all the distribution packages
          uses: actions/download-artifact@v3
          with:
            name: dependencytrees-distributions
            path: dist/
        - name: Publish distribution to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/
            password: ${{ secrets.TEST_PYPI_TOKEN }}
